server:
  port: 8762                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    hostname: peer2
spring:
  application:
    name: microservice-discovery-eureka-double

