server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: microservice-discovery-eureka-double

#  server:
#    enable-self-preservation: false


# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756